-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRmTnX0Hw0gB3S/t2
QooKkvSbmMJb2plKrnJAn6RZXQ6gCgYIKoZIzj0DAQehRANCAARquWu+OKudghjC
LbOsCBMfFvrgFer8jloZ+nGIrs8Pz8Az5JbUeupjhy+byiN6fRrVwPQS7kTSNg5S
n+t4fP+4
-----END PRIVATE KEY-----